/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controle.fun;
import dao.funDAO;

/**
 *
 * @author edvar
 */
public class cadFn extends javax.swing.JFrame {

    /**
     * Creates new form cadFn
     */
    public cadFn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        NOME = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        end = new javax.swing.JLabel();
        cep = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtEnd = new javax.swing.JTextField();
        txtCEP = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cadastrarBT = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titulo.setText("CADASTRO FUNCIONARIO");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 260, 27));

        NOME.setForeground(new java.awt.Color(255, 255, 255));
        NOME.setText("NOME:");
        getContentPane().add(NOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));

        telefone.setForeground(new java.awt.Color(255, 255, 255));
        telefone.setText("TELEFONE:");
        getContentPane().add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        end.setForeground(new java.awt.Color(255, 255, 255));
        end.setText("ENDEREÇO:");
        getContentPane().add(end, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, -1, -1));

        cep.setForeground(new java.awt.Color(255, 255, 255));
        cep.setText("CEP:");
        getContentPane().add(cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 186, -1, -1));

        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("EMAIL:");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 224, -1, -1));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 69, 209, -1));
        getContentPane().add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 107, 188, -1));
        getContentPane().add(txtEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 145, 184, -1));
        getContentPane().add(txtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 183, 223, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 221, 208, -1));

        cadastrarBT.setText("CADASTRAR");
        cadastrarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBTActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 294, 118, 66));

        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 294, 95, 66));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(655, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cadastrarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBTActionPerformed
        
        fun f = new fun();
        funDAO dao = new funDAO();
        
        f.setNome(txtNome.getText());
        f.setTelefone(txtTel.getText());
        f.setEndereco(txtEnd.getText());
        f.setCep(txtCEP.getText());
        f.setEmail(txtEmail.getText());
        dao.create(f);
    }//GEN-LAST:event_cadastrarBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadFn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadFn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadFn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadFn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadFn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NOME;
    private javax.swing.JButton cadastrarBT;
    private javax.swing.JLabel cep;
    private javax.swing.JLabel email;
    private javax.swing.JLabel end;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel telefone;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
